module.exports= {
   USER_ROLE:[
     'BUYER',
     'SELLER'  
   ],
   ORDER_STATUS:[
      'SUCCESS',
      'FAILED',
      'PROCESSING' 
   ],
   EQUIPMENT_STATUS:[
       'AVAILABLE',
       'UNAVAILABLE'
   ],
   PAYMENT_STATUS:[
      'SUCCESS',
      'FAILED'
   ] 
}